### ISSUE TITLE
Bug: sequential_p_values returns p-value > 1.0

### ISSUE THREAD

**Issue by ajithopti** [optimizely/ssrm#11]
ssrm-test version: 0.1.2

The function `sequential_p_values` returns p-value > 1.0

```python
import numpy as np
from ssrm_test import ssrm_test

print(ssrm_test.sequential_p_values([np.array([0.50725726, 0.49274274])], [0.5, 0.5]))
```

outputs
```bash
array([1.00004999])
```

**Comment by michaellindon** [comment]
@ajithopti  Clarifying question, why is the data not integer? This should be user counts.

**Comment by ajithopti** [comment]
> @ajithopti Clarifying question, why is the data not integer? This should be user counts.

Ooh. I assumed it was the observed probabilities, hence floats. However, I think the function should assert that the `data` values are integers.
